#!/usr/bin/env bash

# Exit immediately if a command fails
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$SCRIPT_DIR"

echo "=========================================="
echo "   ERP AI Gateway - Config Generator     "
echo "=========================================="

CONFIG_FILE="config/config.yaml"
mkdir -p config

# Check for force overwrite flag (-f or --force)
FORCE_OVERWRITE=false
AUTO_YES=false

for arg in "$@"; do
    case "$arg" in
        -f|--force)
            FORCE_OVERWRITE=true
            ;;
        -y|--default)
            AUTO_YES=true
            ;;
    esac
done

if [ ! -t 0 ]; then
    AUTO_YES=true
fi

# IMPORTANT FIX: Preserve existing config/config.yaml unless force flag is passed
if [ -f "$CONFIG_FILE" ] && [ "$FORCE_OVERWRITE" = false ]; then
    echo "✔ Active configuration file '$CONFIG_FILE' already exists."
    echo "  Preserving your existing configuration (API keys, ports, node URLs)."
    echo "  (Use ./scripts/setup_config.sh --force to recreate if needed)."
    echo "=========================================="
    exit 0
fi

# Function to generate a random secret key
generate_random_key() {
    if command -v openssl >/dev/null 2>&1; then
        echo "krea_sec_$(openssl rand -hex 16)"
    else
        echo "krea_sec_$(head -c 16 /dev/urandom | xxd -p | tr -d '\n')"
    fi
}

# Default parameter values
DEFAULT_PORT=8080
DEFAULT_TIMEOUT=120
DEFAULT_MAX_PAYLOAD=10
DEFAULT_LOG_LEVEL="info"
DEFAULT_RATE_LIMIT=1000
DEFAULT_MODEL="qwen2.5:0.5b"
DEFAULT_OLLAMA_URLS="http://10.10.3.74:11434"

if [ "$AUTO_YES" = true ]; then
    echo "Creating $CONFIG_FILE with defaults..."
    PORT=${PORT:-$DEFAULT_PORT}
    LOG_LEVEL=${LOG_LEVEL:-$DEFAULT_LOG_LEVEL}
    MODEL=${MODEL:-$DEFAULT_MODEL}
    OLLAMA_URLS=${OLLAMA_URLS:-$DEFAULT_OLLAMA_URLS}
    API_KEY=${API_KEY:-$(generate_random_key)}
else
    echo "Interactive Setup. Press Enter to accept default values in brackets []."
    echo ""

    # 1. Server Port
    read -rp "Server Port [$DEFAULT_PORT]: " INPUT_PORT
    PORT=${INPUT_PORT:-$DEFAULT_PORT}

    # 2. Log Level
    read -rp "Log Level (debug/info/warn/error) [$DEFAULT_LOG_LEVEL]: " INPUT_LOG
    LOG_LEVEL=${INPUT_LOG:-$DEFAULT_LOG_LEVEL}

    # 3. API Key Generation
    read -rp "Generate random secure API Key automatically? (y/n) [y]: " AUTO_GEN_KEY
    AUTO_GEN_KEY=${AUTO_GEN_KEY:-y}

    if [[ "$AUTO_GEN_KEY" =~ ^[Yy] ]]; then
        API_KEY=$(generate_random_key)
        echo "Generated API Key: $API_KEY"
    else
        read -rp "Enter Custom API Key [krea-secret-ai-key-2026]: " INPUT_KEY
        API_KEY=${INPUT_KEY:-krea-secret-ai-key-2026}
    fi

    # 4. Default LLM Model
    read -rp "Default Model Name [$DEFAULT_MODEL]: " INPUT_MODEL
    MODEL=${INPUT_MODEL:-$DEFAULT_MODEL}

    # 5. Ollama Server URLs
    read -rp "Ollama Server URLs (comma separated) [$DEFAULT_OLLAMA_URLS]: " INPUT_OLLAMA
    OLLAMA_URLS=${INPUT_OLLAMA:-$DEFAULT_OLLAMA_URLS}
fi

# Build config/config.yaml content dynamically
cat <<EOF > "$CONFIG_FILE"
# Enterprise AI Platform Gateway Configuration
# Generated by scripts/setup_config.sh

server:
  port: $PORT
  request_timeout_seconds: $DEFAULT_TIMEOUT
  max_payload_size_mb: $DEFAULT_MAX_PAYLOAD
  log_level: "$LOG_LEVEL"

security:
  api_key: "$API_KEY"
  rate_limit:
    requests_per_minute: $DEFAULT_RATE_LIMIT
    burst: 100

prompt:
  directory: "./prompts"

llm:
  provider: "ollama"
  default_model: "$MODEL"
  load_balancing_strategy: "least_in_flight"

  ollama_servers:
EOF

# Parse comma-separated Ollama URLs into YAML array entries
IFS=',' read -ra ADDR <<< "$OLLAMA_URLS"
NODE_INDEX=1
for url in "${ADDR[@]}"; do
    TRIMMED_URL=$(echo "$url" | xargs)
    if [ -n "$TRIMMED_URL" ]; then
        cat <<EOF >> "$CONFIG_FILE"
    - name: "ollama-node-$NODE_INDEX"
      url: "$TRIMMED_URL"
      weight: 1
      max_concurrent: 100
EOF
        NODE_INDEX=$((NODE_INDEX + 1))
    fi
done

echo "=========================================="
echo " ✔ Configuration generated successfully!"
echo " File: $CONFIG_FILE"
echo " API Key: $API_KEY"
echo " Port: $PORT"
echo " Model: $MODEL"
echo "=========================================="
